# Generated by Django 6.0.7 on 2026-07-08 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="McpToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable label (e.g. 'Claude Desktop — laptop').",
                        max_length=120,
                    ),
                ),
                ("secret_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("secret_prefix", models.CharField(max_length=32)),
                (
                    "scopes",
                    models.TextField(
                        default="tools:*",
                        help_text="Comma-separated scopes. Use 'tools:*' for full read-only access, or list specific tools: 'tools:current_time_utc,tools:count_users_since'.",
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Per-minute rate limit. 0 means unlimited (use sparingly).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional hard expiry. Tokens without an expiry are valid until revoked.",
                        null=True,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="mcp_server__created_4e4e1d_idx"),
                    models.Index(fields=["revoked_at"], name="mcp_server__revoked_97fa67_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="McpCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("method", models.CharField(blank=True, default="", max_length=64)),
                ("tool_name", models.CharField(blank=True, default="", max_length=120)),
                ("argument_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Success"),
                            ("auth_failed", "Auth failed"),
                            ("tool_denied", "Tool denied (scope or source)"),
                            ("rate_limited", "Rate limited"),
                            ("bad_request", "Bad request"),
                            ("error", "Handler error"),
                        ],
                        max_length=24,
                    ),
                ),
                ("error", models.CharField(blank=True, default="", max_length=240)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=240)),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="mcp_server.mcptoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="mcp_server__timesta_bba181_idx"),
                    models.Index(
                        fields=["token", "-timestamp"], name="mcp_server__token_i_140288_idx"
                    ),
                    models.Index(fields=["status"], name="mcp_server__status_8cb4b4_idx"),
                ],
            },
        ),
    ]
