# Generated by Django 6.0.7 on 2026-07-08 01:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("agent", "Agent"),
                            ("cron", "Cron"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=16,
                    ),
                ),
                ("trigger_type", models.CharField(blank=True, default="", max_length=64)),
                ("trigger_data", models.JSONField(blank=True, default=dict)),
                ("output", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("capped", "Capped"),
                            ("suppressed", "Suppressed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("suppressed_reason", models.CharField(blank=True, default="", max_length=64)),
                ("model_used", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=10),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-started_at"], name="llm_agentru_kind_3a0fb8_idx"
                    ),
                    models.Index(
                        fields=["trigger_type", "-started_at"],
                        name="llm_agentru_trigger_866a41_idx",
                    ),
                    models.Index(
                        fields=["status", "-started_at"], name="llm_agentru_status_a2a2ca_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LLMToolCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("turn_index", models.PositiveIntegerField()),
                ("tool_name", models.CharField(max_length=120)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.CharField(blank=True, default="", max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="llm.agentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["agent_run_id", "turn_index"],
                "indexes": [
                    models.Index(
                        fields=["agent_run", "turn_index"], name="llm_llmtool_agent_r_f541eb_idx"
                    ),
                    models.Index(
                        fields=["tool_name", "-created_at"], name="llm_llmtool_tool_na_849ffa_idx"
                    ),
                ],
            },
        ),
    ]
